[package]
name = "dma-buf"
version = "0.2.1-alpha.0"
authors = ["Maxime Ripard <maxime@cerno.tech>"]
edition = "2021"
description = "Linux DMA-Buf Abstraction Library"
readme = "README.md"
license-file = "LICENSE"
keywords = ["linux", "dma", "dma-buf"]
categories = ["api-bindings", "os::linux-apis"]
repository = "https://github.com/mripard/dma-buf/"

[dependencies]
libc = "0.2.137"
log = "0.4.17"
memmap = { package = "memmap2", version = "0.5.8" }
nix = "0.26.1"
thiserror = "1.0.37"
